import { useEffect, useState } from "react";
import { createClient } from "@supabase/supabase-js";
const nav = [["home","⌂","Home"],["trade","↗","Trade"],["activity","◷","Activity"],["wallet","▣","Wallet"],["profile","◉","Profile"]];
const supabase = import.meta.env.VITE_SUPABASE_URL && import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ? createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY) : null;
export default function App(){const [page,setPage]=useState("home");const [user,setUser]=useState(null);const [profile,setProfile]=useState(null);useEffect(()=>{if(!supabase)return;supabase.auth.getClaims().then(({data})=>setUser(data?.claims||null));const {data}=supabase.auth.onAuthStateChange((_e,session)=>{setUser(session?.user||null);if(session?.user)loadProfile(session.user.id);else setProfile(null)});return()=>data.subscription.unsubscribe()},[]);async function loadProfile(id){const {data}=await supabase.from("profiles").select("display_name,telegram_username,avatar_url,referral_code").eq("id",id).maybeSingle();setProfile(data||null)}async function signOut(){if(supabase)await supabase.auth.signOut()}return <div className="app-shell"><header className="topbar"><div className="brand"><b>F</b><div><strong>Flexar</strong><small>AI Trades</small></div></div><button className="icon-button" onClick={()=>setPage("profile")}>⌁</button></header><main className="content">{page==="home"&&<Home setPage={setPage}/>} {page==="trade"&&<Trade/>}{page==="activity"&&<Activity/>}{page==="wallet"&&<Wallet/>}{page==="profile"&&<Profile user={user} profile={profile} signOut={signOut}/>}</main><nav className="bottom-nav">{nav.map(([id,icon,label])=><button key={id} className={page===id?"nav active":"nav"} onClick={()=>setPage(id)}><span>{icon}</span><small>{label}</small></button>)}</nav></div>}
function Home({setPage}){return <><section className="hero"><small>TOTAL BALANCE</small><h1>$1,284.60</h1><p className="green">+ $84.60 this week</p><div className="actions"><button onClick={()=>setPage("trade")}>Start AI Trade</button><button className="secondary" onClick={()=>setPage("wallet")}>Wallet</button></div></section><h2>Quick view</h2><div className="grid">{["Available|$1,284.60","Active trades|1","Win rate|78%","Referrals|12"].map(x=>{const [a,b]=x.split("|");return <div className="stat" key={a}><small>{a}</small><strong>{b}</strong></div>})}</div><h2>Recent activity</h2><div className="list"><Row text="TON / USDT · UP" value="+$21.25"/><Row text="TON / USDT · DOWN" value="-$15.00" bad/></div></>}
function Trade(){const [dir,setDir]=useState("UP");const [amount,setAmount]=useState("25");return <><section className="intro"><small>AI TRADE</small><h1>Trade with a clear view.</h1><p>Choose your stake, duration and direction.</p></section><section className="card"><div className="market"><strong>TON / USDT</strong><span>● LIVE</span></div><div className="price"><small>Current price</small><strong>$3.42</strong><em>+2.14%</em></div><label>Direction</label><div className="grid two"><button className={dir==="UP"?"selected":""} onClick={()=>setDir("UP")}>↗ UP</button><button className={dir==="DOWN"?"selected":""} onClick={()=>setDir("DOWN")}>↘ DOWN</button></div><label>Stake</label><div className="grid four">{["10","25","50","100"].map(x=><button key={x} className={amount===x?"selected":""} onClick={()=>setAmount(x)}>${x}</button>)}</div><button className="full">Confirm {dir} trade</button></section></>}
function Activity(){return <><section className="intro"><small>ACTIVITY</small><h1>Your trade history.</h1><p>Track settled and active trades from your Flexar account.</p></section><div className="list"><Row text="TON / USDT · UP · Today 09:12" value="+$21.25"/><Row text="TON / USDT · DOWN · Yesterday 18:40" value="-$15.00" bad/><Row text="TON / USDT · UP · Yesterday 16:21" value="+$8.50"/></div></>}
function Wallet(){return <><section className="intro"><small>WALLET</small><h1>Move funds simply.</h1><p>TON and USDT on TRC-20 are supported.</p></section><section className="hero"><small>PORTFOLIO BALANCE</small><h1>$1,284.60</h1><div className="actions"><button>Deposit</button><button className="secondary">Withdraw</button></div></section><div className="list"><Row text="TON · TON network" value="184.20 TON"/><Row text="USDT · TRC-20" value="654.60 USDT"/></div></>}
function Profile({user,profile,signOut}){return <><section className="profile"><div>{(profile?.display_name||"F").slice(0,1).toUpperCase()}</div><p><small>{profile?.telegram_username?"@"+profile.telegram_username:"Flexar account"}</small><strong>{user?(profile?.display_name||"Connected account"):"Connect Telegram to continue"}</strong></p>{user?<button className="secondary" onClick={signOut}>Sign out</button>:<button className="secondary" onClick={()=>alert("Telegram connection will be enabled through the secure Flexar Telegram authentication flow.")}>Connect</button>}</section><div className="list"><Row text="Notifications" value="Telegram + app"/><Row text="Security" value="Protected"/><Row text="Referral code" value={profile?.referral_code||"—"}/></div></>}
function Row({text,value,bad}){return <div className="row"><span>{text}</span><strong className={bad?"red":"green"}>{value}</strong></div>}